package dev.mtib.aoc.util

object AocDayLoader {
    init {
        Class.forName("dev.mtib.aoc.aoc23.days.Day1")
        Class.forName("dev.mtib.aoc.aoc23.days.Day10")
        Class.forName("dev.mtib.aoc.aoc23.days.Day11")
        Class.forName("dev.mtib.aoc.aoc23.days.Day12")
        Class.forName("dev.mtib.aoc.aoc23.days.Day13")
        Class.forName("dev.mtib.aoc.aoc23.days.Day14")
        Class.forName("dev.mtib.aoc.aoc23.days.Day15")
        Class.forName("dev.mtib.aoc.aoc23.days.Day16")
        Class.forName("dev.mtib.aoc.aoc23.days.Day17")
        Class.forName("dev.mtib.aoc.aoc23.days.Day18")
        Class.forName("dev.mtib.aoc.aoc23.days.Day19")
        Class.forName("dev.mtib.aoc.aoc23.days.Day2")
        Class.forName("dev.mtib.aoc.aoc23.days.Day20")
        Class.forName("dev.mtib.aoc.aoc23.days.Day21")
        Class.forName("dev.mtib.aoc.aoc23.days.Day22")
        Class.forName("dev.mtib.aoc.aoc23.days.Day23")
        Class.forName("dev.mtib.aoc.aoc23.days.Day24")
        Class.forName("dev.mtib.aoc.aoc23.days.Day25")
        Class.forName("dev.mtib.aoc.aoc23.days.Day3")
        Class.forName("dev.mtib.aoc.aoc23.days.Day4")
        Class.forName("dev.mtib.aoc.aoc23.days.Day5")
        Class.forName("dev.mtib.aoc.aoc23.days.Day6")
        Class.forName("dev.mtib.aoc.aoc23.days.Day7")
        Class.forName("dev.mtib.aoc.aoc23.days.Day8")
        Class.forName("dev.mtib.aoc.aoc23.days.Day9")
        Class.forName("dev.mtib.aoc.aoc24.days.Day1")
        Class.forName("dev.mtib.aoc.aoc24.days.Day2")
        Class.forName("dev.mtib.aoc.aoc24.days.Day3")
        Class.forName("dev.mtib.aoc.aoc24.days.Day4")
        Class.forName("dev.mtib.aoc.aoc24.days.Day5")
        Class.forName("dev.mtib.aoc.aoc24.days.Day6")
        Class.forName("dev.mtib.aoc.aoc24.days.Day7")
        Class.forName("dev.mtib.aoc.aoc24.days.Day8")
        Class.forName("dev.mtib.aoc.aoc24.days.Day9")
    }
    
    val allDays: List<dev.mtib.aoc.day.AocDay> = listOf(
        dev.mtib.aoc.aoc23.days.Day1,
        dev.mtib.aoc.aoc23.days.Day10,
        dev.mtib.aoc.aoc23.days.Day11,
        dev.mtib.aoc.aoc23.days.Day12,
        dev.mtib.aoc.aoc23.days.Day13,
        dev.mtib.aoc.aoc23.days.Day14,
        dev.mtib.aoc.aoc23.days.Day15,
        dev.mtib.aoc.aoc23.days.Day16,
        dev.mtib.aoc.aoc23.days.Day17,
        dev.mtib.aoc.aoc23.days.Day18,
        dev.mtib.aoc.aoc23.days.Day19,
        dev.mtib.aoc.aoc23.days.Day2,
        dev.mtib.aoc.aoc23.days.Day20,
        dev.mtib.aoc.aoc23.days.Day21,
        dev.mtib.aoc.aoc23.days.Day22,
        dev.mtib.aoc.aoc23.days.Day23,
        dev.mtib.aoc.aoc23.days.Day24,
        dev.mtib.aoc.aoc23.days.Day25,
        dev.mtib.aoc.aoc23.days.Day3,
        dev.mtib.aoc.aoc23.days.Day4,
        dev.mtib.aoc.aoc23.days.Day5,
        dev.mtib.aoc.aoc23.days.Day6,
        dev.mtib.aoc.aoc23.days.Day7,
        dev.mtib.aoc.aoc23.days.Day8,
        dev.mtib.aoc.aoc23.days.Day9,
        dev.mtib.aoc.aoc24.days.Day1,
        dev.mtib.aoc.aoc24.days.Day2,
        dev.mtib.aoc.aoc24.days.Day3,
        dev.mtib.aoc.aoc24.days.Day4,
        dev.mtib.aoc.aoc24.days.Day5,
        dev.mtib.aoc.aoc24.days.Day6,
        dev.mtib.aoc.aoc24.days.Day7,
        dev.mtib.aoc.aoc24.days.Day8,
        dev.mtib.aoc.aoc24.days.Day9,
    )
}
