name: Run
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/run.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: 23
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build
        env:
          SESSION: ${{ secrets.SESSION }}
          KETCHUP_TOKEN: ${{ secrets.KETCHUP_TOKEN }}
          USER_SNOWFLAKE: ${{ secrets.USER_SNOWFLAKE }}
      - run: ./gradlew test
        env:
          SESSION: ${{ secrets.SESSION }}
          KETCHUP_TOKEN: ${{ secrets.KETCHUP_TOKEN }}
          USER_SNOWFLAKE: ${{ secrets.USER_SNOWFLAKE }}
      - run: rm src/main/resources/day*.txt
      - run: ./gradlew fatJar
      - run: java -jar build/libs/*-all.jar all
        env:
          SESSION: ${{ secrets.SESSION }}
          KETCHUP_TOKEN: ${{ secrets.KETCHUP_TOKEN }}
          USER_SNOWFLAKE: ${{ secrets.USER_SNOWFLAKE }}
      - run: |
          cp build/libs/*-all.jar src/main/resources/.
          cp build/libs/*-all.jar src/main/resources/aoc-kt-latest-all.jar
          rm src/main/resources/day*.txt src/main/resources/results.json src/main/resources/.gitignore src/main/resources/*_progress.png
      - uses: idlefingers/do-space-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: './src/main/resources/'
          SPACE_NAME: ${{ secrets.SPACE_NAME }}
          SPACE_REGION: ${{ secrets.SPACE_REGION}}
          SPACE_ACCESS_KEY_ID: ${{ secrets.SPACE_ACCESS_KEY_ID }}
          SPACE_SECRET_ACCESS_KEY: ${{ secrets.SPACE_SECRET_ACCESS_KEY }}
